image: carlallen/docker:buildx

stages:
    - build

variables:
    IMAGE_NAME: $AZURECR_HOST/my-portfolio

before_script:
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - echo "$AZURECR_PASSWORD" | docker login $AZURECR_HOST -u "$AZURECR_USER" --password-stdin
    - docker buildx create --name builder --use

# Build the Docker image for multiple architectures
build:
    stage: build
    script:
        - VERSION=$(cat VERSION)
        - echo "Building Docker image for $IMAGE_NAME:$VERSION"

        - docker buildx build --push --platform linux/amd64,linux/arm64 -t $IMAGE_NAME:latest -t $IMAGE_NAME:$VERSION .
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Deploy the docker image to kubernetes
deploy:
    stage: deploy
    script:
        - kubectl set image deployment/my-portfolio my-portfolio=$IMAGE_NAME:$VERSION
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
