image: carlallen/docker:buildx

stages:
    - build
    - deploy

variables:
    IMAGE_NAME: $AZURECR_HOST/my-portfolio
    KUBECONFIG_B64: $KUBECONFIG_B64

before_script:
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - echo "$AZURECR_PASSWORD" | docker login $AZURECR_HOST -u "$AZURECR_USER" --password-stdin
    - docker buildx create --name builder --use
    - echo "$KUBECONFIG_B64" | base64 -d > /tmp/kubeconfig
    - export KUBECONFIG=/tmp/kubeconfig

# Build the Docker image for multiple architectures
build:
    stage: build
    script:
        - VERSION=$(cat VERSION)
        - echo "Building Docker image for $IMAGE_NAME:$VERSION"

        - docker buildx build --push --platform linux/amd64,linux/arm64 -t $IMAGE_NAME:latest -t $IMAGE_NAME:$VERSION .
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
          changes:
              - ./VERSION

# Deploy the docker image to kubernetes
deploy:
    stage: deploy
    image: bitnami/kubectl:latest
    script:
        - echo /tmp/config
    # - kubectl set image deployment/my-portfolio my-portfolio=$IMAGE_NAME:$VERSION --namespace homelab
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
