services:
    my-portfolio:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - DASHBOARD_URL=https://dashboard.beenhamow.co.uk
                - ANALYTICS_ID=G-NCDDJ1GR78
        container_name: my-portfolio
        ports:
            - 3000:3000
        restart: unless-stopped
