services:
    dashboard:
        build:
            context: ../
            dockerfile: Dockerfile
        container_name: my-portfolio
        ports:
            - "3000:3000"
        environment:
            - MONGO_URI
            - INSTANCE_ID
            - ANALYTICS_TAG
